# dataset available: https://huggingface.co/datasets/ibm-nasa-geospatial/hls_burn_scars
class_path: GenericNonGeoSegmentationDataModule
init_args:
  batch_size: 4
  num_workers: 8

  dataset_bands:
    - BLUE
    - GREEN
    - RED
    - NIR_NARROW
    - SWIR_1
    - SWIR_2
  output_bands:
    - BLUE
    - GREEN
    - RED
    - NIR_NARROW
    - SWIR_1
    - SWIR_2
  rgb_indices:
    - 0
    - 1
    - 2
  means:
    - 0.033349706741586264
    - 0.05701185520536176
    - 0.05889748132001316
    - 0.2323245113436119
    - 0.1972854853760658
    - 0.11944914225186566
  stds:
    - 0.02269135568823774
    - 0.026807560223070237
    - 0.04004109844362779
    - 0.07791732423672691
    - 0.08708738838140137
    - 0.07241979477437814

  no_data_replace: 0
  no_label_replace: -1
  num_classes: 2
  train_transform:
    - class_path: albumentations.RandomCrop
      init_args:
        height: 224
        width: 224
    - class_path: albumentations.HorizontalFlip
      init_args:
        p: 0.5
    - class_path: ToTensorV2

  test_data_root: <data_path>/validation
  test_label_data_root: <data_path>/validation
  train_data_root: <data_path>/training
  train_label_data_root: <data_path>/training
  val_data_root: <data_path>/validation
  val_label_data_root: <data_path>/validation
  img_grep: "*_merged.tif"
  label_grep: "*.mask.tif"
